import { Curriculum, SyllabusData } from './types';

export const SYLLABUS: Record<Curriculum, SyllabusData> = {
  [Curriculum.IGCSE]: {
    subjects: ['English Language', 'English Literature', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Computer Science', 'Economics'],
    years: ['FM2', 'FM3', 'FM4', 'FM5'],
    units: {
      'English Language': ['Descriptive Writing', 'Narrative Writing', 'Reading & Comprehension', 'Directed Writing'],
      'English Literature': ['Poetry Analysis', 'Prose Study', 'Drama', 'Unseen Text'],
      'Mathematics': ['Algebra', 'Geometry & Trigonometry', 'Statistics & Probability', 'Number & Arithmetic'],
      'Physics': ['Forces & Motion', 'Electricity & Magnetism', 'Waves & Optics', 'Thermal Physics'],
      'Chemistry': ['Atomic Structure', 'Chemical Bonding', 'Organic Chemistry', 'Electrochemistry'],
      'Biology': [
        'Characteristics and classification of living organisms',
        'Organisation of the organism',
        'Movement into and out of cells',
        'Biological molecules',
        'Enzymes',
        'Plant nutrition',
        'Human nutrition',
        'Transport in plants',
        'Transport in animals',
        'Diseases and immunity',
        'Gas exchange in humans',
        'Respiration',
        'Excretion in humans',
        'Coordination and response',
        'Drugs',
        'Reproduction',
        'Inheritance',
        'Variation and selection',
        'Organisms and their environment',
        'Human influences on ecosystems',
        'Biotechnology and genetic modification'
      ],
      'History': ['World War I', 'Rise of Dictatorships', 'Cold War', 'Decolonisation'],
      'Geography': ['Coasts', 'Rivers', 'Population', 'Globalisation'],
      'Computer Science': ['Programming', 'Data Structures', 'Networks', 'Databases'],
      'Economics': ['Supply & Demand', 'Market Structures', 'Macroeconomics', 'International Trade'],
    }
  },
  [Curriculum.IBMYP]: {
    subjects: {
      'Year 1': ['Language & Literature', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Sciences', 'Individuals & Societies', 'Arts', 'Design', 'PHE'],
      'Year 2': ['Language & Literature', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Sciences', 'Individuals & Societies', 'Arts', 'Design', 'PHE'],
      'Year 3': ['Language & Literature', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Sciences', 'Individuals & Societies', 'Arts', 'Design', 'PHE'],
      'Year 4': ['Language & Literature', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Individuals & Societies', 'Arts', 'Design', 'PHE'],
      'Year 5': ['Language & Literature', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Individuals & Societies', 'Arts', 'Design', 'PHE'],
    },
    years: ['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5'],
    units: {
      'Language & Literature': ['Identity & Self-expression', 'Power & Conflict', 'Cultural Diversity', 'Media & Technology'],
      'Mathematics': ['Patterns & Algebra', 'Space & Geometry', 'Quantity', 'Statistics & Probability'],
      'Sciences': ['Ecosystems & Biodiversity', 'Genetics & Heredity', 'Forces & Energy', 'Chemical Reactions'],
      'Biology': [
        'Cells (tissues, organs, systems, structure and function; factors affecting human health; physiology; vaccination)',
        'Organisms (habitat, ecosystems, interdependency, unity and diversity in life forms; energy transfer and cycles [including nutrient, carbon, nitrogen]; classification)',
        'Processes (photosynthesis, cell respiration, aerobic and anaerobic, word and chemical equations)',
        'Metabolism (nutrition, digestion, biochemistry and enzymes; movement and transport, diffusion; osmosis; gas exchange; circulation, transpiration and translocation; homeostasis)',
        'Evolution (life cycles, natural selection; cell division, mitosis, meiosis; reproduction; biodiversity; inheritance and variation, DNA and genetics)',
        'Interactions with environment (tropism, senses, nervous system, receptors and hormones)',
        'Interactions between organisms (pathogens/parasites, predator/prey, food chains and webs; competition, speciation and extinction)',
        'Human interactions with environments (human influences, habitat change or destruction, pollution/ conservation; overexploitation, mitigation of adverse effects)',
        'Biotechnology (genetic modification, cloning; ethical implications, genome mapping and application, 3D tissue and organ printing)'
      ],
      'Chemistry': ['Atomic Structure', 'Bonding & Properties', 'Reactions & Energy', 'Organic Chemistry'],
      'Physics': ['Mechanics', 'Electricity', 'Waves', 'Magnetism & Electromagnetism'],
      'Individuals & Societies': ['Rights & Responsibilities', 'Globalisation', 'Historical Inquiry', 'Economic Systems'],
      'Arts': ['Visual Communication', 'Artistic Process', 'Cultural Context', 'Exhibition'],
      'Design': ['Design Cycle', 'Product Design', 'Digital Design', 'Innovation'],
      'PHE': ['Fitness & Health', 'Team Sports', 'Individual Activities', 'Wellbeing'],
    }
  },
  [Curriculum.IBDP]: {
    subjects: ['Language A: Literature', 'Language B', 'Mathematics AA', 'Mathematics AI', 'Physics', 'Chemistry', 'Biology', 'History', 'Economics', 'Computer Science'],
    years: ['DP Year 1', 'DP Year 2'],
    units: {
      'Language A: Literature': ['Works in Translation', 'Individual Oral', 'Paper 1 Practice', 'Comparative Essay'],
      'Mathematics AA': ['Algebra & Functions', 'Calculus', 'Statistics & Probability', 'Vectors & Geometry'],
      'Physics': ['Mechanics', 'Fields', 'Waves & Optics', 'Thermodynamics'],
      'Chemistry': ['Stoichiometry', 'Periodicity', 'Energetics', 'Organic Chemistry'],
      'Biology': ['Cell Biology', 'Genetics & Evolution', 'Ecology', 'Human Physiology'],
      'History': ['Causes of WWI', 'Rise of Fascism', 'Cold War', 'Decolonisation'],
      'Economics': ['Microeconomics', 'Macroeconomics', 'International Economics', 'Development Economics'],
    }
  }
};

export const UNIT_TOPICS: Record<string, string[]> = {
  'Characteristics and classification of living organisms': ['Characteristics of living organisms', 'Concept and use of a classification system', 'Features of organisms', 'Dichotomous keys'],
  'Organisation of the organism': ['Cell structure and organisation', 'Levels of organisation', 'Size of specimens'],
  'Movement into and out of cells': ['Diffusion', 'Osmosis', 'Active transport'],
  'Biological molecules': ['Biological molecules (Carbohydrates, Fats, Proteins)', 'Structure of DNA', 'Tests for biological molecules'],
  'Enzymes': ['Enzyme action', 'Effects of temperature and pH on enzymes'],
  'Plant nutrition': ['Photosynthesis', 'Leaf structure', 'Mineral requirements'],
  'Human nutrition': ['Diet', 'Alimentary canal', 'Mechanical digestion', 'Chemical digestion', 'Absorption'],
  'Transport in plants': ['Transport in xylem', 'Transpiration', 'Transport in phloem'],
  'Transport in animals': ['Heart', 'Blood and lymphatic vessels', 'Blood'],
  'Diseases and immunity': ['Pathogens and transmission', 'Defences against diseases', 'Immunisation'],
  'Gas exchange in humans': ['Gas exchange surfaces', 'Ventilation of the lungs', 'Effects of smoking'],
  'Respiration': ['Aerobic respiration', 'Anaerobic respiration'],
  'Excretion in humans': ['Excretion', 'Structure and function of the kidneys'],
  'Coordination and response': ['Coordination and response', 'Receptor cells', 'Effector cells', 'Nervous system', 'Sense organs', 'Hormones', 'Homeostasis', 'Tropic responses'],
  'Drugs': ['Drugs', 'Medicinal drugs', 'Misused drugs'],
  'Reproduction': ['Asexual reproduction', 'Sexual reproduction', 'Sexual reproduction in plants', 'Sexual reproduction in humans', 'Sex hormones', 'Methods of birth control', 'Sexually transmitted infections'],
  'Inheritance': ['Chromosomes, genes and proteins', 'Mitosis', 'Meiosis', 'Monohybrid inheritance', 'Co-dominance', 'Sex linkages', 'Protein synthesis'],
  'Variation and selection': ['Variation', 'Adaptive features', 'Selection'],
  'Organisms and their environment': ['Energy flow', 'Food chains and food webs', 'Nutrient cycles', 'Population size'],
  'Human influences on ecosystems': ['Food supply', 'Habitat destruction', 'Pollution', 'Conservation'],
  'Biotechnology and genetic modification': ['Biotechnology', 'Genetic modification'],
  'Cells (tissues, organs, systems, structure and function; factors affecting human health; physiology; vaccination)': ['Cell structure', 'Tissues and organs', 'Organ systems', 'Human health factors', 'Physiology basics', 'Vaccination and immunity'],
  'Organisms (habitat, ecosystems, interdependency, unity and diversity in life forms; energy transfer and cycles [including nutrient, carbon, nitrogen]; classification)': ['Habitats', 'Ecosystems', 'Interdependency', 'Unity and diversity', 'Energy transfer', 'Nutrient cycles', 'Classification'],
  'Processes (photosynthesis, cell respiration, aerobic and anaerobic, word and chemical equations)': ['Photosynthesis', 'Aerobic respiration', 'Anaerobic respiration', 'Chemical equations'],
  'Metabolism (nutrition, digestion, biochemistry and enzymes; movement and transport, diffusion; osmosis; gas exchange; circulation, transpiration and translocation; homeostasis)': ['Nutrition and digestion', 'Biochemistry', 'Enzymes and metabolism', 'Movement and transport', 'Gas exchange', 'Circulation', 'Homeostasis'],
  'Evolution (life cycles, natural selection; cell division, mitosis, meiosis; reproduction; biodiversity; inheritance and variation, DNA and genetics)': ['Life cycles', 'Natural selection', 'Cell division (Mitosis/Meiosis)', 'Reproduction', 'Biodiversity', 'Inheritance', 'DNA and genetics'],
  'Interactions with environment (tropism, senses, nervous system, receptors and hormones)': ['Tropism', 'The senses', 'Nervous system', 'Receptors and hormones'],
  'Interactions between organisms (pathogens/parasites, predator/prey, food chains and webs; competition, speciation and extinction)': ['Pathogens and parasites', 'Predator and prey', 'Food chains and webs', 'Competition', 'Speciation and extinction'],
  'Human interactions with environments (human influences, habitat change or destruction, pollution/ conservation; overexploitation, mitigation of adverse effects)': ['Human influences', 'Habitat destruction', 'Pollution and conservation', 'Overexploitation', 'Mitigation strategies'],
  'Biotechnology (genetic modification, cloning; ethical implications, genome mapping and application, 3D tissue and organ printing)': ['Genetic modification', 'Cloning', 'Ethical implications', 'Genome mapping', '3D Bioprinting'],
  'Descriptive Writing': ['Sensory Language', 'Structural Techniques', 'Figurative Language', 'Atmosphere & Mood'],
  'Poetry Analysis': ['Imagery & Metaphor', 'Rhyme & Rhythm', 'Tone & Voice', 'Context & Theme'],
  'Algebra': ['Linear Equations', 'Quadratic Functions', 'Simultaneous Equations', 'Sequences & Series'],
  'Forces & Motion': ["Newton's Laws", 'Velocity & Acceleration', 'Momentum & Impulse', 'Free Body Diagrams'],
  'Cell Biology': ['Cell Structure', 'Cell Division', 'Transport Mechanisms', 'Microscopy Skills'],
  'Genetics': ['DNA Structure', 'Mendelian Inheritance', 'Mutations', 'Genetic Engineering'],
  'Identity & Self-expression': ['Personal Narrative', 'Language & Identity', 'Cultural Voice', 'Memoir Writing'],
  'Patterns & Algebra': ['Sequences & Series', 'Functions', 'Linear Models', 'Algebraic Proof'],
  'Ecosystems & Biodiversity': ['Food Webs', 'Nutrient Cycles', 'Biodiversity Indices', 'Human Impact'],
  'Chemical Reactions': ['Reaction Types', 'Rates of Reaction', 'Equilibrium', 'Energy Changes'],
  '_default': ['Introduction', 'Core Concepts', 'Application', 'Review & Assessment'],
};

export const DEFAULT_CHANNELS = [
  { name: 'TED-Ed', handle: '@TED-Ed', checked: true },
  { name: 'Crash Course', handle: '@crashcourse', checked: true },
  { name: 'Khan Academy', handle: '@khanacademy', checked: true },
  { name: 'Cognito', handle: '@CognitoEdu', checked: true },
  { name: 'Freesciencelessons', handle: '@freesciencelessons', checked: true },
  { name: 'Cambridge in 5 Minutes', handle: '@CambridgeIn5Minutes', checked: true },
  { name: 'Nucleus Media', handle: '@NucleusMedicalMedia', checked: true },
  { name: 'Peekaboo', handle: '@Peekaboo_Kidz', checked: true },
  { name: 'Amoeba Sisters', handle: '@AmoebaSisters', checked: true },
  { name: 'Science with Hazel', handle: '@ScienceWithHazel', checked: false },
  { name: 'Mr Bruff (English)', handle: '@mrbruff', checked: false },
  { name: 'Physics Online', handle: '@PhysicsOnline', checked: false },
  { name: 'Revision Village (IB)', handle: '@RevisionVillage', checked: false },
];
